version: 3

tasks:
  build:
    desc: Build the application
    cmds:
      - go build -ldflags "-X 'jdk.sh/meta.version=$(gitversion)' -X 'jdk.sh/meta.sha=$(git rev-parse HEAD)' -X 'jdk.sh/meta.date=$(date -R)'" -o gitversion main.go
  install:
    desc: Install the plugin
    deps:
      - build
    cmds:
      - cp gitversion ~/go/bin/gitversion
  run:
    desc: Run the application
    cmds:
      - go run main.go
